### ISSUE TITLE
Fix coverage badge in README

### ISSUE THREAD

**Issue by accraze** [discogs/pymongo-job-queue#5]
For some reason the coverage badge isn't working anymore, but the repo is still on codecov: https://codecov.io/github/discogs/pymongo-job-queue

**Comment by shiv4nsh** [comment]
Is this a private one, like do you have any token for this like in this url: https://img.shields.io/codecov/c/token/YOURTOKEN/github/codecov/example-python.svg

**Comment by accraze** [comment]
@shiv4nsh nope it's not private

**Comment by insomnious0x01** [comment]
From the README.md file I picked up this image [URL](https://img.shields.io/codecov/c/github/discogs/pymongo-job-queue.svg) which leads you to the "coverage|unknown". I looked at other repositories that use similar badges and their badges work because they committed changes to their code within last 6 months. 

Last commit that was picked up by codecov was "Removed sites property from Job example in README  39b271c" which is 2 commits behind this repo. I've read that codecov only reads your source code when you [send a request](https://codecov.io/site/security#when-does-codecov-read-source-code-from-my-repository) for them to look at your repository. I've never used codecov before - how do you send them a request so they look at your repo? Is it part of Travis' build script?

**Comment by feldoh** [comment]
I don't think it's that I've forked it and set up a parallel pipeline to my own account and it's not working even after I upload stuff.

**Comment by feldoh** [comment]
haha, I worked it out; pr incoming.

**Comment by feldoh** [comment]
PR #7 Resolves this issue. It seems to be because the coverage combine blanks out the results then the upload shortcuts to no-op because there is no data. As you can see my PR triggered a codecov comment which is as good a test as any and indeed the version of the badge for my PR seems to work: ![codecov](https://codecov.io/gh/discogs/pymongo-job-queue/pull/7/graph/badge.svg)

**Comment by accraze** [comment]
resolved by #7, thanks everyone!
